---

- hosts: all
  become: true
  tasks:

  - name: update repo index
    apt:
      update_cache: yes      
    when: ansible_distribution in ["Ubuntu", "Debian"]

  - name: install apache2 package
    apt: 
      name: apache2
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: add php support for apache2
    apt:
      name: libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install net-tools for ifconfig
    apt:
      name: net-tools
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: update repo index
    dnf:
      update_cache: yes      
    when: ansible_distribution == "Fedora"

  - name: install httpd package
    dnf: 
      name: httpd
      state: latest
    when: ansible_distribution == "Fedora"

  - name: add php support for httpd
    dnf:
      name: php
      state: latest
    when: ansible_distribution == "Fedora"

  - name: install net-tools for ifconfig
    dnf:
      name: net-tools
      state: latest
    when: ansible_distribution == "Fedora"
