---

- hosts: all
  become: true
  tasks:

  - name: update repo index
    apt:
      update_cache: yes      
    when: ansible_distribution in ["Ubuntu", "Debian"]

  - name: install apache2 along with php support and net-tools packages
    apt: 
      name: 
        - apache2
        - libapache2-mod-php
        - net-tools
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: update repo index
    dnf:
      update_cache: yes      
    when: ansible_distribution == "Fedora"

  - name: install httpd along with php support and net-tools packages 
    dnf: 
      name: 
        - httpd
        - php
        - net-tools
      state: latest
    when: ansible_distribution == "Fedora"
