---

- hosts: all
  become: true
  tasks:

  - name: install updates (Ubuntu)
    apt:
      update_cache: yes
      upgrade: dist
    when: ansible_distribution == "Ubuntu"

  - name: install updates (Fedora)
    dnf:
      update_cache: yes
      update_only: yes
    when: ansible_distribution == "Fedora"

- hosts: web_servers
  become: true
  tasks:

  - name: install apache2, php packages for Ubuntu Web servers
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install httpd, php packages for Fedora Web servers
    dnf:
      name: 
        - httpd
        - php
      state: latest
    when: ansible_distribution == "Fedora"
