---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (Ubuntu)
    apt:
      update_cache: yes
      upgrade: dist
    when: ansible_distribution == "Ubuntu"

  - name: install updates (Fedora)
    dnf:
      update_cache: yes
      update_only: yes
    when: ansible_distribution == "Fedora"

- hosts: web_servers
  become: true
  tasks:

  - name: install apache2, php packages for Web servers (Ubuntu)
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install httpd, php packages for Web servers (Fedora)
    dnf:
      name: 
        - httpd
        - php
      state: latest
    when: ansible_distribution == "Fedora"

- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb pkg (Ubuntu)
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

- hosts: file_servers
  become: true
  tasks:
  
  - name: install samba package
    package:
      name: samba
      state: latest



